// Dwg_HelloWorld.h  file  =================
// generated by pfodWeb Designer Arduino Export V1.1.5 -- 19th September 2025
#ifndef DWG_HelloWorld_H
#define DWG_HelloWorld_H
// Arduino code for drawing: HelloWorld
// Generated from pfod drawing HelloWorld.json
/*   
 * (c)2025 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#include <pfodDrawing.h>
 
class Dwg_HelloWorld : public pfodDrawing {
  public:
    Dwg_HelloWorld();
    void init();
    bool sendDwg(); // returns true if dwg sent else false i.e. not this dwg's loadCmd
    bool processDwgCmds(); // return true if handled else false

  protected:
    void sendFullDrawing();
    void sendUpdate();
    void sendIndexedItems();
  private:
    bool initialized;      

};

extern Dwg_HelloWorld dwg_HelloWorld;
#endif
// ================= end of Dwg_HelloWorld.h  file
