#ifndef PFOD_MAIN_DRAWING_H
#define PFOD_MAIN_DRAWING_H

// pfodMainDrawing.h file  =================
// generated by pfodWeb Designer Arduino Export V1.1.5 -- 19th September 2025
// This file sets the mainDwg 
// Generated from pfod drawing HelloWorld.json
/*   
 * (c)2025 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#include <pfodDrawing.h>

void initDrawings();
extern pfodDrawing& mainDwg; // defined in pfodMainDrawing.cpp, the variable that pfodMainMenu.cpp expects to define the main drawing

#endif  
