// pfodMainDrawing.cpp  file ==============
// generated by pfodWeb Designer Arduino Export V1.1.5 -- 19th September 2025
// This file sets the mainDwg  and supplies initDrawings()

// Generated from pfod drawing HelloWorld.json

/*   
 * (c)2025 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */

#include <pfodDrawing.h>
#include <pfodDebugPtr.h>

#include "Dwg_HelloWorld.h"

// #define DEBUG
static Print* debugPtr = NULL;   // local to this file

static bool initialized = false;

pfodDrawing& mainDwg = dwg_HelloWorld; // the variable that pfodMainMenu.cpp expects to define the main drawing


// initialize all drawings here.  adds them to parser linked list of drawings
void initDrawings() {
  if (initialized) {
    return;
  }
  initialized = true;  
  (void)debugPtr; // suppress not used warning
#ifdef DEBUG
  debugPtr = getDebugPtr();
#endif
  dwg_HelloWorld.init();
}
