name=pfodParser
version=5.1.1
author=Matthew Ford
maintainer=Matthew Ford
sentence=A library to parse pfod messages sent from pfodApp / pfodWeb.html and includes pfodWeb.html which connects via Serial, BLE, Tcp/Ip and HTTP to display interactive menus and GUI's in your browser.
paragraph=pfodParser serves GUI's to pfodWeb.html and handles the user's commands.  pfodWeb.html is open source and does not need an internet connection. It runs in your browser and connects via Serial, BLE, TCP/IP socket or HTTP to display an interactive GUI to control your board, completely defined by your board sketch. 
category=Device Control, Communication
url=https://github.com/drmpf/pfodParser
architectures=*
includes=pfodParser.h,pfodSecurity.h,pfodControl.h,pfodDelay.h,pfodDwgs.h,pfodEEPROM.h,pfodStreamString.h,ESP_PicoW_LittleFSsupport.h,ESP_PicoW_pfodAppServer.h,ESP_PicoW_pfodWebServer.h